### ISSUE TITLE
Remove duplicate IP address detection when adding new cameras

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#367]
Currently it is not possible to add more then source from the same IP address.  This is problematic for video servers or testing video streams from the same camera.

**Comment by hallamjeff** [comment]
The check currently inspects the full path, including the host, port and path. Is it just the host IP address check that should be removed or the whole path check?

**Comment by curtishall** [comment]
We should be probably remove this check entirely.  I'm not sure why it was added to begin with, after adding the check it is problematic for video servers with the same IP address with multiple RTSP paths or NAT'd cameras over the same IP address so the check was modified a bit to see if the paths were different.

If you feel up to a PR deleting the check entirely I'd be okay with that.  We shouldn't limit a user on how they want to add cameras....if they want to add the same camera 10 times then that's up to them :)

**Comment by hallamjeff** [comment]
I'm pretty new to being a contribute. I have made the changes that I think are necessary to remove the check completely and it works for identical MJPEG paths (success!) For an RTSP path, the same IP can be used now (success!), but ONLY if there is variation in the port and/or filesystem path. The handling of this case is what I can't resolve on my own, an identical RTSP cam will throw a generic pop-up error window which states "err ajax". I can't find where in the code it is initiating this.

Can I put in the PR as-is since it does remove the check? Is it reasonable to assume that a user may add the same IP but not the exact same full path of IP + port + path ?
