### ISSUE TITLE
TimeStamp Overlay

### ISSUE THREAD

**Issue by manjotsc** [bluecherrydvr/bluecherry-apps#400]
Hi,

I notice when I download a playback file there is no timestamp overlay on video. I couldn't find any settings for it. But in live view there is. How can I enable it for video recording?

Thanks,

**Comment by curtishall** [comment]
We do not support text overlay at the moment, mainly because this will generate excessive CPU usage and most (all?) IP cameras will overlay the OSD text (date/time) for you.

Also - Please use forums.bluecherrydvr.com in the future, GitHub Issues is for reporting bugs, anything else needs to be on the forums.
